#define RTC_PRELOAD_SEC 36
#define RTC_PRELOAD_MIN 23
#define RTC_PRELOAD_HOUR 17
#define RTC_PRELOAD_DOM 17
#define RTC_PRELOAD_DOW 6
#define RTC_PRELOAD_DOY 77
#define RTC_PRELOAD_MONTH 3
#define RTC_PRELOAD_YEAR 2012
