#define RTC_PRELOAD_SEC 28
#define RTC_PRELOAD_MIN 1
#define RTC_PRELOAD_HOUR 13
#define RTC_PRELOAD_DOM 24
#define RTC_PRELOAD_DOW 2
#define RTC_PRELOAD_DOY 115
#define RTC_PRELOAD_MONTH 4
#define RTC_PRELOAD_YEAR 2012
