#define RTC_PRELOAD_SEC 31
#define RTC_PRELOAD_MIN 26
#define RTC_PRELOAD_HOUR 11
#define RTC_PRELOAD_DOM 28
#define RTC_PRELOAD_DOW 3
#define RTC_PRELOAD_DOY 88
#define RTC_PRELOAD_MONTH 3
#define RTC_PRELOAD_YEAR 2012
