#define PLAYFIELDSIZE 130
	#define PLAYFIELDCANARY 0xaa
	uint8_t playfield[PLAYFIELDSIZE + 1] = { 8, 16,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,
				 PLAYFIELDCANARY
				  };