#define RTC_PRELOAD_SEC 42
#define RTC_PRELOAD_MIN 24
#define RTC_PRELOAD_HOUR 9
#define RTC_PRELOAD_DOM 3
#define RTC_PRELOAD_DOW 5
#define RTC_PRELOAD_DOY 34
#define RTC_PRELOAD_MONTH 2
#define RTC_PRELOAD_YEAR 2012
